databases:
  - name: joineazy-db
    databaseName: joineazy_db
    user: joineazy_user
    plan: free

services:
  - type: web
    name: joineazy-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node migrate.js && npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: joineazy-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://joineazy-task1-nine.vercel.app
      - key: GOOGLE_CLIENT_ID
        value: 359442548382-jl3228fv1hud96pr7r9lbgnptgri86f4.apps.googleusercontent.com
